/*1*/
SELECT FNAME +' '+ LNAME AS NAME 
FROM EMPLOYEES
WHERE LNAME LIKE 'M%'

/*2*/
SELECT NAME 
FROM COUNTRIES C JOIN CUSTOMERS CU
ON C.COUNTRY_ID = CU.COUNTRY_ID
UNION
SELECT C.NAME 
FROM COUNTRIES C JOIN DEPARTMENTS D
ON C.COUNTRY_ID = D.COUNTRY_ID

/*3*/
SELECT O.ORDER_ID, ORDER_DATE, SUM(QUANTITY*UNIT_PRICE) AS TOTAL
FROM ORDERS O JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
WHERE YEAR(ORDER_DATE) = 2000
GROUP BY O.ORDER_ID, ORDER_DATE

/*4*/
SELECT O.ORDER_ID, ORDER_DATE, SUM(QUANTITY*UNIT_PRICE) AS TOTAL,
DATEADD(DAY,7,ORDER_DATE) AS PAID_DATE
FROM ORDERS O JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.ORDER_ID, ORDER_DATE

/*5*/
SELECT FNAME +' '+ LNAME AS NAME, 
COUNT(ORDER_ID) AS BROY
FROM EMPLOYEES E LEFT JOIN ORDERS O 
ON E.EMPLOYEE_ID=O.EMPLOYEE_ID
GROUP BY FNAME +' '+ LNAME
ORDER BY BROY DESC

/*6*/
SELECT FNAME FROM EMPLOYEES 
INTERSECT 
SELECT FNAME FROM CUSTOMERS

/*7*/
SELECT NAME FROM COUNTRIES C JOIN CUSTOMERS CU 
ON C.COUNTRY_ID = CU.COUNTRY_ID
INTERSECT
SELECT C.NAME FROM COUNTRIES C JOIN DEPARTMENTS D
ON C.COUNTRY_ID = D.COUNTRY_ID


/*8*/
SELECT FNAME FROM EMPLOYEES
EXCEPT 
SELECT FNAME FROM CUSTOMERS

/*9*/
SELECT DISTINCT NAME AS COUNTRY 
FROM COUNTRIES C JOIN CUSTOMERS CU
ON C.COUNTRY_ID = CU.COUNTRY_ID
LEFT JOIN DEPARTMENTS D
ON C.COUNTRY_ID=D.COUNTRY_ID
WHERE NOT EXISTS(SELECT * FROM COUNTRIES CO JOIN DEPARTMENTS D
ON CO.COUNTRY_ID= D.COUNTRY_ID
WHERE CO.NAME = C.NAME)

/*10*/
SELECT FNAME+' '+LNAME AS NAME, HIRE_DATE 
FROM EMPLOYEES
WHERE HIRE_DATE = (SELECT MAX(HIRE_DATE) FROM EMPLOYEES)

/*11*/
SELECT * FROM
(SELECT TOP 1 WITH TIES FNAME+' '+LNAME AS NAME,
SUM(UNIT_PRICE * QUANTITY) AS TOTAL
FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMERS_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI 
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY FNAME +' '+ LNAME
ORDER BY TOTAL) MIN_ORDER
UNION
SELECT * FROM
(SELECT TOP 1 WITH TIES FNAME+' '+LNAME AS NAME,
SUM(UNIT_PRICE * QUANTITY) AS TOTAL
FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMERS_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI 
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY FNAME +' '+ LNAME
ORDER BY TOTAL DESC)
MAX_ORDER

/*12*/
SELECT FNAME +' '+ LNAME AS NAME, SALARY
FROM EMPLOYEES E 
WHERE SALARY > ALL(SELECT AVG(SALARY) FROM EMPLOYEES EM
WHERE E.DEPARTMENT_ID=EM.DEPARTMENT_ID)

/*13*/
SELECT TOP 3 WITH TIES NAME, AVG(UNIT_PRICE * QUNTITY)AS TOTAL
FROM PRODUCTS P JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY NAME
ORDER BY TOTAL DESC

/*14*/
SELECT TOP 1 WITH TIES ORDER_ID, SUM(UNIT_PRICE*QUANTITY) AS TOTAL
FROM ORDER_ITEMS
GROUP BY ORDER_ID
ORDER BY TOTAL DESC



