/*1*/
create view customerorders_1
AS 
select c.fname +' '+ c.lname as customer, O.ORDER_ID, O.ORDER_DATE 
FROM ORDERS O, CUSTOMERS C
SELECT * FROM customerorders_1

/*2*/
alter view customerorders_1 AS
select C.FNAME +' '+ C.LNAME as customer, O.ORDER_ID, O.ORDER_DATE 
E.FNAME +' '+ E.LNAME AS EMPLOYEe
FROM ORDERS O, CUSTOMERS C, EMPLOYEES E
/*3*/
alter view customerorders_1 as
select c.FNAME +' '+ c.LNAME as customer, O.ORDER_ID, O.ORDER_DATE,
E.FNAME +' '+ E.LNAME as employee
from ORDERS O, CUSTOMERS C, EMPLOYEES E
WHERE E.EMPLOYEE _ID = 167
SELECT * FROM customerorders_1 

/*4*/
create view emp_ord AS 
select E.FNAME +' '+ E.LNAME AS NAME, SUM(OI.QUANTITY * OI.UNIT_PRICE)AS SUMA 
FROM EMPLOYEES E, ORDER_ITEMS OI, ORDERS O
WHERE E.EMPLOYEE_ID = O.EMPLOYEE_ID AND O.ORDER_ID = OI.ORDER_ID 
GROUP BY E.EMPLOYEE_ID, E.FNAME +' '+E.LNAME
SELECT * FROM EMP_ORD
ORDER BY SUMA DESC

/*5*/
SELECT * FROM EMP_ORD
ORDER BY SUMA DESC
/*6*/
create view emp_1 as 
select fname +' '+ lname as name, salary/12 as m_salary,DEPARTMENT_ID
from EMPLOYEES 

SELECT * FROM EMPL_1
WHERE NAME LIKE 'Г%'

UPDATE EMPL_1
SET DEPARTMENT_ID = 90
WHERE NAME = 'Георги Гелов'

create view DEP_90 AS 
select FNAME, LNAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90
WITH CHECK OPTION 

UPDATE DEP_90
SET DEPARTMENT_ID = 100
WHERE FNAME = 'Георги Гелов'

/*6.2*/
Create view manager_order as
select FNAME, LNAME, sum(UNIT_PRICE*QUANTITY) AS TOTAL
FROM EMPLOYEES E JOIN ORDERS O
ON E.EMPLOYEE_ID = O.EMPLOYEE_ID
JOIN ORDER_ITEMS OI
ON OI.ORDER_ID = O.ORDER_ID 
WHERE E.EMPLOYEE_ID IN (SELECT MANAGER_ID FROM EMPLOYEES)
GROUP BY FNAME, LNAME
SELECT * FROM manager_order

/*6.3*/

CREATE VIEW JOB_DATE AS 
SELECT JOB_TITLE, MIN(HIRE_DATE) AS  MIN_DATE, MAX(HIRE_DATE) AS MAX_DATE
FROM JOBS J, EMPLOYEES E 
ON J.JOB_ID = E.JOB_ID
GROUP BY JOB_TITLE

SELECT * FROM JOB_DATE
/*6.4*/

/*6.5*/
create view EMPL_DEP_ORD AS 
SELECT E.EMPLOYEE_ID,NAME, COUNT(ORDER_ID)AS BROY
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
LEFT JOIN ORDERS  O
ON E.EMPLOYEE_ID = O.EMPLOYEE_ID
GROUP BY E.EMPLOYEE_ID,NAME 
SELECT * FROM EMPL_DEP_ORD

/*6.6*/
Create VIEW COUNTRY_REGION_1 AS 
SELECT C.NAME AS COUNTRY, R.NAME AS REGION 
FROM COUNTRIES C JOIN REGIONS R
ON C.COUNTRY_ID = REGION_ID
LEFT JOIN CUSTOMERS CU
ON C.COUNTRY_ID = CU.COUNTRY_ID
LEFT JOIN DEPARTMENS D 
ON C.COUNRY_ID = D.COUNTRY_ID
WHERE CU.COUNTRY_ID IS NULL AND D.COUNTRY_ID IS NULL
SELECT * FROM COUNTRY_REGION 

/*6.7*/
CREATE VIEW DEP_EMPL_2 AS
SELECT NAME, COUNT(EMPLOYEE_ID)AS BROY, MAX(SALARY)AS MAX_SALARY 
FROM 
